# Generated by Django 5.1 on 2024-08-28 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('cantidad_base', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AjustePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ajustada', models.PositiveIntegerField()),
                ('motivo', models.TextField()),
                ('fecha_ajuste', models.DateField(auto_now_add=True)),
                ('comprado_fuera', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.PositiveIntegerField()),
                ('fecha_pedido', models.DateField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.articulo')),
            ],
        ),
    ]
