# Generated by Django 5.1 on 2024-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0003_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
