# Generated by Django 5.1 on 2024-08-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0004_reservation_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
